### ISSUE TITLE
Reward Address validation widget

### ISSUE THREAD

**Issue by achiurizo** [subspace/subspace-docs#120]
Should explore adding a reward address validator widget so people can check that they are using the correct address.

**Comment by ryyeung** [comment]
Started looking into this and found some resources on GH to implement this, will continue working on it:
https://github.com/ryanralph/altcoin-address](https://github.com/ryanralph/altcoin-address
https://github.com/ognus/wallet-address-validator](https://github.com/ognus/wallet-address-validator
https://github.com/ognus/wallet-address-validator/issues/59
