### ISSUE TITLE
Fix button CSS on CLI Page

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-docs#123]
Download Buttons on CLI page are a but off, just need some styling fixes. 

![image](https://user-images.githubusercontent.com/31865152/204569338-04ebc00d-0731-4ef1-9a08-54dffb4d5934.png)

Ideally the buttons will be in the same line with some spacing based on the webpages size.

**Comment by SageJasinski** [comment]
Hi, I am not sure if this has been fixed yet but I did some work on the buttons and submitted a PR if you'd like to check it out.

**Comment by achiurizo** [comment]
closed by #125 thanks @SageJasinski
