### ISSUE TITLE
Add small guide for Tmux, Screen, & Docker for CLI

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-docs#131]
In the CLI Github repo we give a brief tutorial with Tmux, it would be good to replicate something similar for the CLI Docs page. 

Users have also mentioned a desire to run the cli in docker if this is possible. 

- [x] Add Tmux tutorial - Closed by #142 
- [x] Add Scree tutorial - Closed by #142 
- [x] Add Docker tutorial

**Comment by ryyeung** [comment]
Installed and testing CLI instructions for Tmux before adding instructions into Docs.

**Comment by ImmaZoni** [comment]
#142 Partially closed this issue. We still need to add Docker instruction

**Comment by TESLAOPUnix** [comment]
I am new to open source and docker but can I still try to work in the docker instruction issue

**Comment by EmilFattakhov** [comment]
Completed!
