### ISSUE TITLE
download link not working in cli.md

### ISSUE THREAD

**Issue by AnimeshKumar923** [subspace/subspace-docs#137]
download link is not visible in the cli.md 

path of file = docs/protocol/cli.md

**Comment by achiurizo** [comment]
@AnimeshKumar923 Thanks for the report! Could you please share more information on what are you seeing? This is what I see currently on the site:

![image](https://user-images.githubusercontent.com/24772/208155318-dd0c6050-8306-44f5-a2c0-214c12acfe4b.png)


Is this what you are referring to?

**Comment by AnimeshKumar923** [comment]
Oh! I forgot to check the website first and made changes to the markdown file instead. Misinterpretation from my side. I apologize for this.
