### ISSUE TITLE
Change screen and tmux commands

### ISSUE THREAD

**Issue by extSunset** [subspace/subspace-docs#164]
I suggest using `screen -D -R -S farming` instead of `screen -S farming` in the documentation.  Some create multiple screens and then have trouble finding the right one. Here is an excerpt from the screen's documentation:
```
-D -R
    Attach here and now. In detail this means: If a session is running, then reattach. If necessary
    detach and logout remotely first. If it was not running create it and notify the user. This is
    the author's favorite. 
```

I'm not familiar with tmux, but perhaps it should give the similar behavior:
`tmux new-session -A -D -s farming`

**Comment by postmeback** [comment]
I would like to contribute here. Can I get any help ?

**Comment by jim-counter** [comment]
> I would like to contribute here. Can I get any help ?

Hi! Sure, please read through this [forum post](https://forum.subspace.network/t/docs-contest-enhance-our-documentation-and-win-250/1523?u=jim-counter). Note that the PR has to be of high enough quality to be merged to be eligible for a prize. Thanks and good luck.

**Comment by postmeback** [comment]
Thanks for the reply. Just wanted to understand, do I have to set the project locally, or is it hosted somewhere?

I was unable to find any URL for the docs.

**Comment by jim-counter** [comment]
> Thanks for the reply. Just wanted to understand, do I have to set the project locally, or is it hosted somewhere?
> 
> I was unable to find any URL for the docs.

The docs are hosted in this GitHub repository. There is a step-by-step guide [here](https://docs.subspace.network/docs/community/contribute/) on how to update them.

**Comment by extSunset** [comment]
Is it worth bringing this in as an addition to the existing instructions?
For example:

Create new screen using a socket file named farming
```
$ screen -S farming
```
Move process to background by detaching
```
Ctrl+d a OR ⌘+d a (Mac)
```
To re-attach
```
$ screen -r farming
```
Alternatively, you can use the following single command to both create (if not exists already) and attach to a session:
```
screen -D -R -S farming
```
To delete farming session
```
$ screen -S farming -X quit
```
