### ISSUE TITLE
[Discussion] The Return of Versioning in Our Documentation: Thoughts?

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-docs#183]
## 🔄 Proposal: Streamlined Documentation Versioning

In the early stages of our platform, we had a comprehensive versioning system for all documentation releases. Users could select from different versions `x`, `y`, or `z` using a dropdown menu. While helpful, this approach led to an extensive expansion of our documentation codebase. 

Faced with these challenges, we made the decision to remove versioning entirely.

As we progress, version-specific documentation for our users will be important for those who may be developing or using the Subspace Network. Thus, I propose reintroducing a more streamlined and manageable versioning system. This system will be structured around two main categories: `Latest` and `Pre-Release`, aligning with our GitHub release conventions. This approach allows us to maintain a current, production version (`Latest`), and an up-to-date, development version (`Pre-Release`) of our docs.

### 💡 The Benefits

- 🎯 **Lean Codebase**: Our proposed versioning strategy will keep our codebase lean and manageable.
- 📘 **User-Friendly**: Users retain access to version-specific documentation.
- ⚖️ **Balanced Approach**: This change balances user needs and efficient code management.

### ⚠️ Heads Up!

- While this initiative promises to be relatively easy and quick to implement, it may lead to some historical links breaking.
- Additionally, to avoid an avalanche 🏔️ of work later on, we should roll out this change **prior** to integrating localization into the documentation

Would love to hear your thoughts, @EmilFattakhov , @jim-counter , and everyone in our wider open-source community! 👥

**Comment by EmilFattakhov** [comment]
I second the idea @ImmaZoni, great proposal!

Even though some users might find this confusing, I believe this would be advantageous for majority of them. I like the idea of giving them a choice of using either of releases, as I frequently see some users being tempted to check out and try pre-releases.

**Comment by jim-counter** [comment]
This seems like a great idea @ImmaZoni, let's crack on with it.
