### ISSUE TITLE
Update Docker Compose commands to v2

### ISSUE THREAD

**Issue by jim-counter** [subspace/subspace-docs#228]
Docker Compose v1 was [deprecated a while ago](https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation). The advanced CLI Docker documentation should be updated so that any commands of the form `docker-compose` should become `docker compose`.

For example:
 `docker-compose up` -> `docker compose up`
and
`docker-compose logs --tail=1000 -f` -> `docker compose logs --tail=1000 -f`

**Comment by PurpleM0ney** [comment]
https://github.com/subspace/subspace-docs/compare/main...PurpleM0ney:subspace-docs:patch-1

Done!

**Comment by gonner22** [comment]
Thanks, guys for adding my suggestion.

Topper

**Comment by EmilFattakhov** [comment]
Fixed by [PR 235](https://github.com/subspace/subspace-docs/pull/235) and [238](https://github.com/subspace/subspace-docs/pull/238)!
