### ISSUE TITLE
Add a section with useful links, communities and resources

### ISSUE THREAD

**Issue by EmilFattakhov** [subspace/subspace-docs#261]
- Provide information about community resources, forums, groups, and chats. 
- List contacts for technical support, learning, and assistance.

**Comment by hairtail** [comment]
Can I create a repo named awesome-subspace for this feature and keep `docs.subspace.network` used for docs (developer first) only? The new created repo will maintain a curated list of Subspace code and resources like core repo, explorer, docs, dapps, wallets, exchanges, tools etc.

**Comment by EmilFattakhov** [comment]
I think it's better to keep farming instructions, developer documentation, and useful resources in the same place, at least for now @hairtail. What do you think about modifying [this page](https://docs.subspace.network/docs/community/), which is a part of documentation, but not polluting developer/farming docs?

**Comment by hairtail** [comment]
> I think it's better to keep farming instructions, developer documentation, and useful resources in the same place, at least for now @hairtail. What do you think about modifying [this page](https://docs.subspace.network/docs/community/), which is a part of documentation, but not polluting developer/farming docs?

Sounds great.

**Comment by EmilFattakhov** [comment]
Done with adding the community page
