### ISSUE TITLE
Correct Gemini-3g Endpoint in `Wallets` Guide. 

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-docs#315]
**Issue Description**
The current Subwallet guide contains outdated information regarding the addition of a custom network. Specifically, the guide lists the RPC endpoint for the Gemini-3G network incorrectly.

**Required Changes**
Current Endpoint: `wss://rpc.gemini-3g.subspace.network`
Updated Endpoint: `wss://rpc-1.gemini-3g.subspace.network`

**Comment by EmilFattakhov** [comment]
Thanks Justin, closing the issue with a merge of https://github.com/subspace/subspace-docs/pull/322
