### ISSUE TITLE
Add rpc page (list of supported rpc methods, usage) in developer part to help interact/query with Subspace network

### ISSUE THREAD

**Issue by hairtail** [subspace/subspace-docs#316]

**Comment by hairtail** [comment]
If we agree on this proposal, I'd like to open a PR for this feature request.

**Comment by EmilFattakhov** [comment]
I think it's updated now @hairtail, if you think there's something more to add - please go for it!

**Comment by EmilFattakhov** [comment]
You're actually right - we haven't updated the dev RPC. Would appreciate you help there 🥇
