### ISSUE TITLE
Feature Request : Add FAQ Section  in Documentation  

### ISSUE THREAD

**Issue by hardiktheprogrammer** [subspace/subspace-docs#394]
Add Section  Frequently  Technical Asked Questions (FAQ) section to the Subspace documentation will serve as a valuable resource for users, contributors, and developers. FAQs provide concise answers to common queries, streamlining the learning process ,  Privacy Questions and troubleshooting efforts

- Troubleshooting Aid:
- Privacy Question 
-  inDepth Technical Question

**Comment by jim-counter** [comment]
Note that we already have a "Common Problems" section here: https://docs.subspace.network/docs/farming-&-staking/farming/common_problems

**Comment by hardiktheprogrammer** [comment]
> Note that we already have a "Common Problems" section here: https://docs.subspace.network/docs/farming-&-staking/farming/common_problems

got it
