### ISSUE TITLE
Read.me contributing links are all incorrect

### ISSUE THREAD

**Issue by jrwashburn** [subspace/subspace-docs#49]
All links under Contributing in the Read.me are HTTP 404 - dead end for potential contributors. 

https://github.com/subspace/subspace-docs/blob/main/.github/CODE_OF_CONDUCT.md
https://github.com/subspace/subspace-docs/blob/main/.github/CONTRIBUTING.md
https://github.com/subspace/subspace-docs/blob/main/.github/TRANSLATE.md
https://github.com/subspace/subspace-docs/blob/main/.github/DEVELOPMENT.md

**Comment by ImmaZoni** [comment]
Thank you for posting this issue! I will get this fixed in the next PR :)
