### ISSUE TITLE
Add: Community Resources

### ISSUE THREAD

**Issue by skylordafk** [subspace/subspace-docs#8]
Subspace is the first protocol to completely resolve the blockchain trilemma [without compromise.](https://medium.com/@solgas/subspace-%D1%8D%D1%82%D0%BE-%D0%BF%D0%B5%D1%80%D0%B2%D1%8B%D0%B9-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D1%81%D1%82%D1%8C%D1%8E-%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B8%D0%B2%D1%88%D0%B8%D0%B9-%D1%82%D1%80%D0%B8%D0%BB%D0%B5%D0%BC%D0%BC%D1%83-%D0%B1%D0%BB%D0%BE%D0%BA%D1%87%D0%B5%D0%B9%D0%BD%D0%B0-%D0%B1%D0%B5%D0%B7-%D0%BA%D0%BE%D0%BC%D0%BF%D1%80%D0%BE%D0%BC%D0%B8%D1%81%D1%81%D0%BE%D0%B2-84aceca19504) written by [@solgas](https://discord.com/channels/864285291518361610/867846783908708352/948772810589880321)

[[FAQ translated to Russian](https://docs.google.com/document/d/17LwoBVP6POgaI18oajyI9xsi3nSJDtS7O-TvKSoHQwo/edit)](https://docs.google.com/document/d/17LwoBVP6POgaI18oajyI9xsi3nSJDtS7O-TvKSoHQwo/edit) by Artem Frolow

[[How to get started farming in Russian](https://vmelbit.medium.com/%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D0%BC%D1%81%D1%8F-%D1%84%D0%B5%D1%80%D0%BC%D0%B5%D1%80%D0%B0%D0%BC%D0%B8-subspace-network-5bacab106755)](https://[vmelbit](https://discord.com/channels/864285291518361610/867846783908708352/949234936781627433).medium.com/%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D0%BC%D1%81%D1%8F-%D1%84%D0%B5%D1%80%D0%BC%D0%B5%D1%80%D0%B0%D0%BC%D0%B8-subspace-network-5bacab106755) by [vmelbit](https://discord.com/channels/864285291518361610/867846783908708352/949234936781627433) 

<img width="503" alt="Screen Shot 2022-03-04 at 3 30 55 PM" src="https://user-images.githubusercontent.com/89288441/156844520-d5ded283-e8fb-4789-ad89-fcddabb67485.png">

**Comment by ImmaZoni** [comment]
Thank you 💯 

Note: you doubled your markdown so when its copied theres issues.
